### ISSUE TITLE
feature request: allow users to specify options in a config file

### ISSUE THREAD

**Issue by nilesjohnson** [kaz-utashiro/sdif#1]
I like a different colormap since I use light-on-dark terminal colors.  I also would like to have `--cdif` on by default.  Since different users will have different preferences, a config file makes sense.

I've done a simple version of colormap config files on these branches:

https://github.com/nilesjohnson/sdif/tree/custom-colormaps
https://github.com/nilesjohnson/cdif/tree/custom-colormaps

If possible, it would be great to read all options from a single config file.

**Comment by kaz-utashiro** [comment]
Thanks for your comments, and more thanks for using them.
1. Please try to use SDIFOPTS to set personal default, at this time.
2. I have a plan to adopt rc-file handling from my **greple** command.  Then you can make your custom options as you like, as well as favorite default.  Please look at **greple** to see if that would match to your wish.  Perl extensible feature won't be necessary, though.
3. I want to make or use general interface to define user-customizable option, which can be used for any command written in any language, some day.
4. I have no idea about config file so far.  I can't think of smart way which works with command option handling consistently.

I've been using these cdif / sdif / greple commands for long time, mainly for my own purpose.  Recently I brushed them up for 500 pages English to Japanese translation work, and those commands are really helpful.  I'm working quite hard on the project right now, and have no time to enjoy programming.  So please forgive me for having some delay.

**Comment by nilesjohnson** [comment]
Thanks for providing these tools -- I think they should be more widely used :)
1. > Please try to use SDIFOPTS to set personal default, at this time.
   
   I didn't notice SDIFOPTS -- thanks for the suggestion.  A separate file is a little easier to maintain, but this is useful for now.
2. > ... Then you can make your custom options as you like, as well as favorite default. Please look at greple to see if that would match to your wish. ... 
   
   this kind of rc-file handling sounds like a good idea. Even better (related to your next point) is to read similar options from a single file.  I will look at greple.
3. > I want to make or use general interface to define used-customized option, which can be used for any command written in any language, some day.
   
   This sounds daunting!  But a single config file for the commands you've written would be a useful start.  The difficult part, to my mind, is how to allow specifying the same value for multiple options, as in `FIELD1=FIELD2=...=COLOR`.  It looks like YAML has functionality for this already though, using node anchors/references.  I'll see if I can get it to work.
4. > I have no idea about config file so far. I can't think of smart way which works with command option handling consistently.
   
   While thinking about this, I came across [Getopt::ArgvFile](http://search.cpan.org/dist/Getopt-ArgvFile/).  It aims to read a config file and effectively add its contents as if they had been passed as arguments.  Unfortunately it's a bit old, and doesn't look to be standard.

> I'm working quite hard on the project right now, and have no time to enjoy programming. So please forgive me for having some delay.

No problem -- I'm just happy I stumbled across your work!

**Comment by kaz-utashiro** [comment]
These are more-than-20-years-old commands written in perl4 syntax.  So I researched similar functionality before working on them to improve, but I could not find satisfying tools.

This is the blog entry at that time.  Written in Japanese, but you can read command names at least.  Hope it helps.

http://utashiro.hatenablog.com/entry/2013/12/28/114121

**Comment by kaz-utashiro** [comment]
It's been a long time.  I completely refactored greple and implemented rc/module loading as a separate module; Getopt::EX. cdif/sdif is updated to use it when available and reads  ~/.cdifrc and ~/.sdifrc files on invocation.  In these files, default option can be defined as:

```
option default --cm ...
```

Please take a look at [develop](https://github.com/kaz-utashiro/greple/tree/develop) branch of greple.  I hope you like it.  Any comments are welcome.

I think appropriate installer is necessary for them, but need to learn some more to do it.

Also the latest cdif/sdif is using default colors visible even on dark settings.

**Comment by kaz-utashiro** [comment]
This repository is totally moved to https://github.com/kaz-utashiro/sdif-tools integrated with other tools.  It is CPAN ready, and can be installed by `cpanm App::sdif`.  sdif now has automatic color setting feature.  It works only on macOS, though.
